version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_dealership
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/car_dealership
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - app-network

volumes:
  postgres_data:
